before_script: 
  - gem install rake
  - bundle install
  - bundle exec rake db:config
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
services:
  - postgresql
language: ruby
rvm:
  - 2.3.1